<?php 
$collection=$block->_prepareLayout();?>
<table>
  <thead>

    <tr><a href="<?php echo $this->getUrl()."mit/form/register";?>"> Add </a></tr>
    <tr>
		<th>Action</th>
		<th>Name</th>
		<th>Email</th>
		<th>Phone No</th>
		<th>Message</th>
    </tr>
  </thead>
  <tbody>
		<?php foreach($collection as $data): ?>
	<tr>
	   <td>
	       <?php 
		   $id = $data->getId();
		   ?>
		   <a href="<?php echo $this->getUrl()?>mit/form/edit?id=<?php echo $id;?>"> Edit </a>
		   <a href="<?php echo $this->getUrl()?>mit/form/Delete?id=<?php echo $id;?>"> Delete <?php 
		   
		   ?></a>
		   
	   </td>
	   <td><?php echo $data->getName(); ?></td>
	   <td><?php echo $data->getEmail(); ?></td>
	   <td><?php echo $data->getPhoneNo();?></td>
	   <td><?php echo $data->getMessage();?></td>
	</tr>
		<?php endforeach; ?>
  </tbody>  
</table> 


