<a href="<?php echo $this->getUrl()."mit/form/demo";?>"> Back</a>

<html>
<body>

<form action="<?php echo $this->getUrl('mit/form/register');?>" method="post">
Name: <input type="text" name="name" required><br>
E-mail: <input type="email" name="email" required><br>
Phone no: <input type="text" name="phone" required><br>
Message: <input type="text" name="message" required><br>
<input type="submit">
</form>

</body>
</html>
